export const cities = [
  "Agrabad",
  "Bangla",
  "Barisal",
  "Bazar",
  "Chittagong",
  "Comilla",
  "Delta",
  "Dhaka",
  "Hossain",
  "Jessore",
  "Kabi",
  "Kazipur",
  "Mymensingh",
  "Narayanganj",
  "Rajshahi",
  "Tejgaon",
  "Uttara",
  "Barguna",
  "Barisāl",
  "Bhandaria",
  "Bhola",
  "Burhanuddin",
  "Gaurnadi",
  "Jhalokati",
  "Lalmohan",
  "Mathba",
  "Mehendiganj",
  "Nalchiti",
  "Patuakhali",
  "Pirojpur",
  "Bandarban",
  "Bandarban",
  "Bibir Hat",
  "Brahmanbaria",
  "Chandpur",
  "Chhagalnaiya",
  "Cox's Bazar",
  "Feni",
  "Hajiganj",
  "Khagrachhari",
  "Lakshām",
  "Lakshmipur",
  "Manikchari",
  "Nabinagar",
  "Noakhali",
  "Patiya",
  "Raipur",
  "Ramganj",
  "Rangamati",
  "Raojan",
  "Sandwip",
  "Satkania",
  "Teknaf",
  "Azimpur",
  "Bajitpur",
  "Bhairab Bazar",
  "Char Bhadrasan",
  "Char Golora",
  "Dohar",
  "Faridpur",
  "Gazipur",
  "Gopalganj",
  "Joymontop",
  "Khanbaniara",
  "Kishoregonj",
  "Kishorganj",
  "Madaripur",
  "Manikganj",
  "Mirzapur",
  "Munshiganj",
  "Nagarpur",
  "Narayanganj",
  "Narsingdi",
  "Palang",
  "Paltan",
  "Parvez Ali",
  "Parvez Ali Hossain",
  "Rajbari",
  "Ramnagar",
  "Sakhipur",
  "Sayani",
  "Shariatpur",
  "Sonargaon",
  "Tangail",
  "Tangail",
  "Tungi",
  "Tungipara",
  "Bagerhat",
  "Bhatpara Abhaynagar",
  "Bheramara",
  "Chuadanga",
  "Jhenaidah",
  "Jhingergacha",
  "Kalia",
  "Kalīganj",
  "Kesabpur",
  "Khulna",
  "Kushtia",
  "Magura",
  "Meherpur",
  "Morrelgonj",
  "Narail",
  "Nowlamary",
  "Phultala",
  "Sarankhola",
  "Satkhira",
  "Satkhira",
  "Ujalpur",
  "Uttar Char Fasson",
  "Gafargaon",
  "Jamalpur",
  "Jamalpur",
  "Muktagacha",
  "Netrakona",
  "Sarishabari",
  "Sherpur",
  "Bera",
  "Bogra",
  "Chapai Nababganj",
  "Ishurdi",
  "Joypur Hat",
  "Joypurhat",
  "Mahasthangarh",
  "Naogaon",
  "Natore",
  "Nawabganj",
  "Pabna",
  "Pabna",
  "Par Naogaon",
  "Puthia",
  "Rajshahi",
  "Saidpur",
  "Shahzadpur",
  "Shibganj",
  "Sirajganj",
  "Badarganj",
  "Chilmari",
  "Dinajpur",
  "Dinajpur",
  "Gaibandha",
  "Kurigram",
  "Lalmonirhat",
  "Lalmonirhat District",
  "Nageswari",
  "Nilphamari Zila",
  "Panchagarh",
  "Parbatipur",
  "Pīrgaaj",
  "Rangpur",
  "Thakurgaon",
  "Thakurgaon",
  "Baniachang",
  "Chhatak",
  "Habiganj",
  "Jahedpur",
  "Maulavi Bazar",
  "Maulvibazar",
  "Sunamganj",
  "Sylhet",
];

export const questionArr = [
  {
    question: "কি চাচ্ছেন?",
    radioOptions: ["বাসা ভাড়া দিতে", "বাসা কিনতে"],
  },
  {
    question: "কি ভাড়া দিবেন ?",
    radioOptions: [
      "ফ্লাট",
      "আপার্টমেন্ট",
      "ছেলেদের মেস",
      "মেয়েদের মেস",
      "সাবলেট",
      "ডুপ্লেক্স",
      "ফরেনার ",
      "পেয়িং গেস্ট",
    ],
  },
  {
    question: "কি বিক্রি করবেন ?",
    radioOptions: [
      "ফ্লাট",
      "আপার্টমেন্ট",
      "ছেলেদের মেস",
      "মেয়েদের মেস",
      "সাবলেট",
      "ডুপ্লেক্স",
      "ফরেনার ",
      "পেয়িং গেস্ট",
    ],
  },
  {
    question: "কয় তলায় ?",
    dropOptions: ["১", "২", "৩", "৪", "৫", "৬", "৭ ", "৮", "৯", "১০", "১১"],
  },
  {
    question: "কয় রুম?",
    dropOptions: ["১", "২", "৩", "৪", "৫", "৬", "৭ ", "৮", "৯", "১০", "১১"],
  },
  {
    question: "টয়লেট/ওয়াশরুম কয়টি ?",
    dropOptions: ["১", "২", "৩", "৪", "৫", "৬", "৭ ", "৮", "৯", "১০", "১১"],
  },
  {
    question: "এটাচ টয়লেটসহ বেডরুম কয়টি ?",
    dropOptions: ["১", "২", "৩", "৪", "৫", "৬", "৭ ", "৮", "৯", "১০", "১১"],
  },
  {
    question: "বারান্দা কয়টি ?",
    dropOptions: ["১", "২", "৩", "৪", "৫", "৬", "৭ ", "৮", "৯", "১০", "১১"],
  },
  {
    question: "ড্রয়িং/ডাইনিং এটাচ নাকি আলাদা ?",
    radioOptions: ["এটাচ", "আলাদা"],
  },
  {
    question: "এলপি গ্যাস নাকি লাইনের গ্যাস ?",
    radioOptions: ["এলপি", "লাইন"],
  },
  {
    question: "মাসিক ভাড়া কত ?",
  },
  {
    question: "এডভান্স কত ?",
  },
  {
    question: "বাসার ছবি সিলেক্ট করুন",
  },
  {
    question: "বাসার এড্রেস (বিভাগ)?",
    dropOptions: [
      "চট্টগ্রাম",
      "রাজশাহী",
      "খুলনা",
      "বরিশাল",
      "সিলেট",
      "ঢাকা",
      "রংপুর",
      "ময়মনসিংহ",
    ],
  },
  {
    question: "বাসার এড্রেস (এলাকা)?",
  },
  {
    question: "আপনার কন্টাক্ট নাম্বার দিন",
  },
];

export const questionList = [
  // {
  //   question: "কি চাচ্ছেন?",
  //   radioOptions: [
  //     {
  //       id: 1,
  //       value: '',
  //       label: "বাসা ভাড়া দিতে",
  //     },
  //     {
  //       id: 2,
  //       value: '',
  //       label: "বাসা কিনতে",
  //     },
  //   ],
  // },
  {
    question: "কি ভাড়া দিবেন ?",
    value: 'type',
    radioOptions: [
      { id: 1, label: "ফ্লাট" },
      { id: 2, label: "আপার্টমেন্ট" },
      { id: 3, label: "ছেলেদের মেস" },
      { id: 4, label: "মেয়েদের মেস" },
      { id: 5, label: "সাবলেট" },
      { id: 6, label: "ডুপ্লেক্স" },
      { id: 7, label: "ফরেনার আপার্টমেন্ট" },
      { id: 8, label: "পেয়িং গেস্ট" },
    ],
  },

  {
    question: "কয় তলায় ?",
    value: 'floor',
    dropOptions: [
      { id: 1, label: "১" },
      { id: 2, label: "২" },
      { id: 3, label: "৩" },
      { id: 4, label: "৪" },
      { id: 5, label: "৫" },
      { id: 6, label: "৬" },
      { id: 7, label: "৭" },
      { id: 8, label: "৮" },
      { id: 9, label: "৯" },
      { id: 10, label: "১০" },
      { id: 11, label: "১১" },
    ],
  },
  {
    question: "কয় রুম?",
    value: 'rooms',
    dropOptions: [
      { id: 1, label: "১" },
      { id: 2, label: "২" },
      { id: 3, label: "৩" },
      { id: 4, label: "৪" },
      { id: 5, label: "৫" },
      { id: 6, label: "৬" },
      { id: 7, label: "৭" },
      { id: 8, label: "৮" },
      { id: 9, label: "৯" },
      { id: 10, label: "১০" },
      { id: 11, label: "১১" },
    ],
  },
  {
    question: "টয়লেট/ওয়াশরুম কয়টি ?",
    value: 'toilet',
    dropOptions: [
      { id: 1, label: "১" },
      { id: 2, label: "২" },
      { id: 3, label: "৩" },
      { id: 4, label: "৪" },
      { id: 5, label: "৫" },
      { id: 6, label: "৬" },
      { id: 7, label: "৭" },
      { id: 8, label: "৮" },
      { id: 9, label: "৯" },
      { id: 10, label: "১০" },
      { id: 11, label: "১১" },
    ],
  },
  {
    question: "এটাচ টয়লেটসহ বেডরুম কয়টি ?",
    value: 'attached toilet',
    dropOptions: [
      { id: 1, label: "১" },
      { id: 2, label: "২" },
      { id: 3, label: "৩" },
      { id: 4, label: "৪" },
      { id: 5, label: "৫" },
      { id: 6, label: "৬" },
      { id: 7, label: "৭" },
      { id: 8, label: "৮" },
      { id: 9, label: "৯" },
      { id: 10, label: "১০" },
      { id: 11, label: "১১" },
    ],
  },
  {
    question: "বারান্দা কয়টি ?",
    value: 'balcony',
    dropOptions: [
      { id: 1, label: "১" },
      { id: 2, label: "২" },
      { id: 3, label: "৩" },
      { id: 4, label: "৪" },
      { id: 5, label: "৫" },
      { id: 6, label: "৬" },
      { id: 7, label: "৭" },
      { id: 8, label: "৮" },
      { id: 9, label: "৯" },
      { id: 10, label: "১০" },
      { id: 11, label: "১১" },
    ],
  },
  {
    question: "ড্রয়িং/ডাইনিং এটাচ নাকি আলাদা ?",
    value: 'attached drawing/dining',
    radioOptions: [
      { id: 1, label: "এটাচ" },
      { id: 2, label: "আলাদা" },
    ],
  },
  {
    question: "এলপি গ্যাস নাকি লাইনের গ্যাস ?",
    value: 'gas',
    radioOptions: [
      { id: 1, label: "এলপি" },
      { id: 2, label: "লাইন" },
    ],
  },
  {
    question: "মাসিক ভাড়া কত ?",
    inputTypeNumber: true,
    value: 'monthly rent'
  },
  {
    question: "এডভান্স কত ?",
    inputTypeNumber: true,
    value: 'advance'
  },

  {
    question: "বাসার ছবি সিলেক্ট করুন",
    value: 'images',
    selectImages: true
  },

  {
    question: "বাসার এড্রেস",
    inputTypeNumber: false,
    dropOptionsDivision: [
      { id: 1, label: "চট্টগ্রাম" },
      { id: 2, label: "রাজশাহী" },
      { id: 3, label: "খুলনা" },
      { id: 4, label: "বরিশাল" },
      { id: 5, label: "সিলেট" },
      { id: 6, label: "ঢাকা" },
      { id: 7, label: "রংপুর" },
      { id: 8, label: "ময়মনসিংহ" },
    ],
    dropOptionsZilla: [
      {
        id: 1, division: 'CHATTOGRAM', districts: [
          { subId: 1, city: "CHATTOGRAM" }, 
          { subId: 2, city: "COX’S  BAZAR" }, 
          { subId: 3, city: "BANDARBAN" }, 
          { subId: 4, city: "RANGAMATI" }, 
          { subId: 5, city: "NOAKHALI" },
          { subId: 6, city: "FENI" },
          { subId: 7, city: "CUMILLA" },
          { subId: 8, city: "CHANDPUR" },
          { subId: 9, city: "BRAHMMANBARIA" },
          { subId: 10, city: "KHAGRACHHARI" },
          { subId: 11, city: "LAKSHMIPUR" }
        ]
      }
    ],
    dropOptionsUpoZilla: [
      {
        subId: 1, city: "CHATTOGRAM", upozillas: [
          {subIdUpo: 1, upozilla: "Karnaphuli"} 
        ]
      }
    ],
    value: 'address'
  },

  {
    question: "আপনার কন্টাক্ট নাম্বার দিন",
    inputTypeNumber: true,
    value: 'contact no'
  },
];
