
export const cities = [
"Agrabad",
"Bangla",
"Barisal",
"Bazar",
"Chittagong",
"Comilla",
"Delta",
"Dhaka",
"Hossain",
"Jessore",
"Kabi",
"Kazipur",
"Mymensingh",
"Narayanganj",
"Rajshahi",
"Tejgaon",
"Uttara",
"Barguna",
"Barisāl",
"Bhandaria",
"Bhola",
"Burhanuddin",
"Gaurnadi",
"Jhalokati",
"Lalmohan",
"Mathba",
"Mehendiganj",
"Nalchiti",
"Patuakhali",
"Pirojpur",
"Bandarban",
"Bandarban",
"Bibir Hat",
"Brahmanbaria",
"Chandpur",
"Chhagalnaiya",
"Cox's Bazar",
"Feni",
"Hajiganj",
"Khagrachhari",
"Lakshām",
"Lakshmipur",
"Manikchari",
"Nabinagar",
"Noakhali",
"Patiya",
"Raipur",
"Ramganj",
"Rangamati",
"Raojan",
"Sandwip",
"Satkania",
"Teknaf",
"Azimpur",
"Bajitpur",
"Bhairab Bazar",
"Char Bhadrasan",
"Char Golora",
"Dohar",
"Faridpur",
"Gazipur",
"Gopalganj",
"Joymontop",
"Khanbaniara",
"Kishoregonj",
"Kishorganj",
"Madaripur",
"Manikganj",
"Mirzapur",
"Munshiganj",
"Nagarpur",
"Narayanganj",
"Narsingdi",
"Palang",
"Paltan",
"Parvez Ali",
"Parvez Ali Hossain",
"Rajbari",
"Ramnagar",
"Sakhipur",
"Sayani",
"Shariatpur",
"Sonargaon",
"Tangail",
"Tangail",
"Tungi",
"Tungipara",
"Bagerhat",
"Bhatpara Abhaynagar",
"Bheramara",
"Chuadanga",
"Jhenaidah",
"Jhingergacha",
"Kalia",
"Kalīganj",
"Kesabpur",
"Khulna",
"Kushtia",
"Magura",
"Meherpur",
"Morrelgonj",
"Narail",
"Nowlamary",
"Phultala",
"Sarankhola",
"Satkhira",
"Satkhira",
"Ujalpur",
"Uttar Char Fasson",
"Gafargaon",
"Jamalpur",
"Jamalpur",
"Muktagacha",
"Netrakona",
"Sarishabari",
"Sherpur",
"Bera",
"Bogra",
"Chapai Nababganj",
"Ishurdi",
"Joypur Hat",
"Joypurhat",
"Mahasthangarh",
"Naogaon",
"Natore",
"Nawabganj",
"Pabna",
"Pabna",
"Par Naogaon",
"Puthia",
"Rajshahi",
"Saidpur",
"Shahzadpur",
"Shibganj",
"Sirajganj",
"Badarganj",
"Chilmari",
"Dinajpur",
"Dinajpur",
"Gaibandha",
"Kurigram",
"Lalmonirhat",
"Lalmonirhat District",
"Nageswari",
"Nilphamari Zila",
"Panchagarh",
"Parbatipur",
"Pīrgaaj",
"Rangpur",
"Thakurgaon",
"Thakurgaon",
"Baniachang",
"Chhatak",
"Habiganj",
"Jahedpur",
"Maulavi Bazar",
"Maulvibazar",
"Sunamganj",
"Sylhet"
]

export const questionArr = [
    {
        question: 'কি চাচ্ছেন?',
        radioOptions: ['rent', 'sell']
    },
    {
        question: 'কি ভাড়া দিবেন ?',
        radioOptions: [ 'Flat', 'ApartMent', 'Male mess', 'Female mess', 'Sublet', 'Duplex', 'Foreigner Apartment', 'Paying Guest' ]

    },
    {
        question: 'কি বিক্রি করবেন ?',
        radioOptions: [ 'Flat', 'ApartMent','Duplex', 'Foreigner Apartment']

    },
    {
        question: 'কয় তলায় ?'
    },
    {
        question: 'টয়লেট/ওয়াশরুম কয়টি ?'
    },
    {
        question: 'এটাচ টয়লেটসহ বেডরুম কয়টি ?'
    },
    {
        question: 'বারান্দা কয়টি ?'
    },
    {
        question: 'ড্রয়িং/ডাইনিং এটাচ নাকি আলাদা ?',
        radioOptions: [ 'এটাচ', 'আলাদা' ] 
    },
    {
        question: 'এলপি গ্যাস নাকি লাইনের গ্যাস ?',
        radioOptions: [ 'এলপি', 'লাইন' ]
    },
    {
        question: 'মাসিক ভাড়া কত ?'
    },
    {
        question: 'এডভান্স কত ?'
    },
    {
        question: 'বাসার এড্রেস (শহর)?'
    },
    {
        question: 'বাসার এড্রেস (এলাকা)?'
    },
    {
        question: 'আপনার কন্টাক্ট নাম্বার দিন'
    }
]