
//landing page
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const CHANGE_BED = 'CHANGE_BED'
export const CHANGE_BATH = 'CHANGE_BATH'
export const CHANGE_LOWER_LIMIT = 'CHANGE_LOWER_LIMIT'
export const CHANGE_UPPER_LIMIT = 'CHANGE_UPPER_LIMIT'
export const CHANGE_PROPERTY_TYPE = 'CHANGE_PROPERTY_TYPE'


//header

export const SHADOW = 'SHADOW';
export const POSITION = 'POSITION' 

//adDetials

export const CHANGE_IMAGE_1 = 'CHANGE_IMAGE_1'
export const CHANGE_IMAGE_2 = 'CHANGE_IMAGE_2'
export const CHANGE_IMAGE_3 = 'CHANGE_IMAGE_3'
export const CHANGE_IMAGE_4 = 'CHANGE_IMAGE_4'
//export const UPDATE_IMAGE = 'UPDATE_IMAGE'


//adsubmit

export const SUBMIT_NEW_ADD_REQUEST = 'SUBMIT_NEW_ADD_REQUEST'
export const SUBMIT_NEW_ADD_SUCCESS = 'SUBMIT_NEW_ADD_SUCCESS'
export const SUBMIT_NEW_ADD_FAILED = 'SUBMIT_NEW_ADD_FAILED'

//getad

export const GET_USER_ADD_REQUEST = 'GET_USER_ADD_REQUEST'
export const GET_USER_ADD_SUCCESS = 'GET_USER_ADD_SUCCESS'
export const GET_USER_ADD_FAILED = 'SUBMIT_NEW_ADD_FAILED'

//signin

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILED = 'SIGNIN_FAILED'

//signup

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'

//logout

export const USER_LOGOUT = 'USER_LOGOUT'




