
//landing page
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const CHANGE_BED = 'CHANGE_BED'
export const CHANGE_BATH = 'CHANGE_BATH'
export const CHANGE_LOWER_LIMIT = 'CHANGE_LOWER_LIMIT'
export const CHANGE_UPPER_LIMIT = 'CHANGE_UPPER_LIMIT'
export const CHANGE_PROPERTY_TYPE = 'CHANGE_PROPERTY_TYPE'


//adDetials

export const CHANGE_IMAGE_1 = 'CHANGE_IMAGE_1'
export const CHANGE_IMAGE_2 = 'CHANGE_IMAGE_2'
export const CHANGE_IMAGE_3 = 'CHANGE_IMAGE_3'
export const CHANGE_IMAGE_4 = 'CHANGE_IMAGE_4'
//export const UPDATE_IMAGE = 'UPDATE_IMAGE'


//adsubmit

export const SUBMIT_NEW_AD_REQUEST = 'SUBMIT_NEW_AD_REQUEST'
export const SUBMIT_NEW_AD_SUCCESS = 'SUBMIT_NEW_AD_SUCCESS'
export const SUBMIT_NEW_AD_FAILED = 'SUBMIT_NEW_AD_FAILED'

//delete an add

export const DELETE_AD_REQUEST = 'DELETE_AD_REQUEST'
export const DELETE_AD_SUCCESS = 'DELETE_AD_SUCCESS'
export const DELETE_AD_FAILED = 'DELETE_AD_FAILED'

//delete an add

export const UPDATE_AD_REQUEST = 'UPDATE_AD_REQUEST'
export const UPDATE_AD_SUCCESS = 'UPDATE_AD_SUCCESS'
export const UPDATE_AD_FAILED = 'UPDATE_AD_FAILED'

//getuserad

export const GET_USER_AD_REQUEST = 'GET_USER_AD_REQUEST'
export const GET_USER_AD_SUCCESS = 'GET_USER_AD_SUCCESS'
export const GET_USER_AD_FAILED = 'GET_USER_AD_FAILED'

//get ad details

export const GET_AD_DETAILS_REQUEST = 'GET_AD_DETAILS_REQUEST'
export const GET_AD_DETAILS_SUCCESS = 'GET_AD_DETAILS_SUCCESS'
export const GET_AD_DETAILS_FAILED = 'GET_AD_DETAILS_FAILED'

//signin

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILED = 'SIGNIN_FAILED'
export const SIGNIN_LOGGEDOUT = 'SIGNIN_LOGGEDOUT'

//signup

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const SIGNUP_LOGGEDOUT = 'SIGNUP_LOGGEDOUT'

//logout

export const USER_LOGOUT = 'USER_LOGOUT'

//divisions
export const GET_DIVISIONS_REQUEST = 'GET_DIVISIONS_REQUEST'
export const GET_DIVISIONS_SUCCESS = 'GET_DIVISIONS_SUCCESS'
export const GET_DIVISIONS_FAILED = 'GET_DIVISIONS_FAILED'

//districts
export const GET_DISTRICTS_REQUEST = 'GET_DISTRICTS_REQUEST'
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICTS_SUCCESS'
export const GET_DISTRICTS_FAILED = 'GET_DISTRICTS_FAILED'

//thanas
export const GET_THANAS_REQUEST = 'GET_THANAS_REQUEST'
export const GET_THANAS_SUCCESS = 'GET_THANAS_SUCCESS'
export const GET_THANAS_FAILED = 'GET_THANAS_FAILED'
//postCodes
export const GET_POSTCODES_REQUEST = 'GET_POSTCODES_REQUEST'
export const GET_POSTCODES_SUCCESS = 'GET_POSTCODES_SUCCESS'
export const GET_POSTCODES_FAILED = 'GET_POSTCODES_FAILED'




